name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Get version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version is $VERSION"

      - name: Zip distribution directory
        run: |
          mkdir -p release
          cd dist
          zip -r ../release/dist.zip ./*

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/dist.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"
          body: |
            Release for version v${{ env.VERSION }}.
