name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Get version
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Get last version
        id: get_last_tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

      - name: Get commits
        id: get_commits
        run: |
          if [ "$LAST_TAG" != "v0.0.0" ]; then
            COMMITS=$(git log ${LAST_TAG}..HEAD --oneline)
            echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          else
            echo "No previous tag found, skipping commit list." >> $GITHUB_ENV
            echo "COMMITS=No previous tag found" >> $GITHUB_ENV
          fi

      - name: Zip distribution directory
        run: |
          mkdir -p release
          zip -r release/dist.zip dist

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/dist.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"
          body: |
            ## Changes since v${{ env.LAST_TAG }}:
            
            ${{ env.COMMITS }}